--- 
- name: Configure Apache
  hosts: all
  become: true
  tasks:
  
    - name: Domain Join 
      apt

    - name: Install Apache
      apt: 
        name: apache2
        state: present
        update_cache: yes

    - name: Copy over the directory with the web page contents 
      copy:
        src: /var/www/html
        dest: /var/www/html
    
    - name: Start and Enable Apache
      systemd:
        name: apache2
        state: started
        enabled: true